### ISSUE TITLE
"Cancel" and "Clear" button for search bar

### ISSUE THREAD

**Issue by whitneywhitehill15** [Southwestern-Higher-Learning/TutorFrontEnd#34]
According to [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/bars/search-bars/) the search bar should have a button on the search bar for the user to exit the search or clear the search. Create button(s) to make this possible.

**Comment by Daniel-Wh** [comment]
Reviewed issue and played around with some of the options in Searchbar but as it turns out, we automatically have a clear icon in Searchbar and if the user presses on any part of the screen that isn't the search board, the keyboard dismisses. Going to keep the same behavior for now. Closing issue.
